// Generated by CoffeeScript 1.6.2
/*
# Visualizer:
*/


(function() {
  var Visualizer;

  Visualizer = (function() {
    Visualizer.prototype.arrayify = function(obj) {
      if (obj instanceof Array) {
        return obj;
      } else {
        return [obj];
      }
    };

    function Visualizer(_arg) {
      var algorithm, breakpoints, controls, inputters, pseudocode, variables, viewers;

      pseudocode = _arg.pseudocode, variables = _arg.variables, breakpoints = _arg.breakpoints, controls = _arg.controls, inputters = _arg.inputters, viewers = _arg.viewers, algorithm = _arg.algorithm;
      this.active = false;
      if (!(this.variables instanceof Array)) {
        this.variables = [this.variables];
      }
      if (typeof pseudocode === 'string') {
        this.$pseudocode = $("#" + pseudocode);
      }
    }

    Visualizer.prototype.generate = function() {
      var inputter, name, v, _i, _len, _ref, _ref1;

      if (this.active) {
        this.clear();
      }
      _ref = this.variables;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        v = _ref[_i];
        this.vars[v] = void 0;
      }
      _ref1 = this.inputters;
      for (name in _ref1) {
        inputter = _ref1[name];
        this.vars[name] = inputter.getInput();
      }
      this.runAlgorithm(algorithm);
      this.active = true;
      return this.showFrame();
    };

    return Visualizer;

  })();

}).call(this);
